---
- name: install packages
-hosts: all
   tasks:
    package:
      name: "{{bzip2, 7-zip}}"
      state: installed
    - name: install vim, Notepad++
      action: command:sudo apt-get install vim, notepad++
    - name: Install git
      yum: 
        name: git
        state: present
    -name: Deploy website from git
     git:
        repo: https://github.com/Reshma4896/TestGit.git

...  
